name: Release and publish to Npm
on:
  push:
    tags:
      - 'v*'
jobs:
  release_and_publish:
    name: Create release and publish to Npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} RELEASE
          draft: false
          prerelease: false

      - name: Publish to Npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
